<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nc_siteessentials"
 *
 * Auto generated by Extension Builder 2014-11-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Site Essentials',
	'description' => 'This extension contains basic site functionality like a xml sitemap, easy way to manage the Google Analytics code and robots.txt on rootpage level',
	'category' => 'plugin',
	'author' => 'Arek van Schaijk',
	'author_email' => 'arek@netcreators.nl',
	'state' => 'beta',
	'internal' => '0.0.0',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.4.3',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);