<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nc_siteessentials"
 *
 * Auto generated by Extension Builder 2014-11-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Site Essentials',
	'description' => 'This extension contains basic site functionality like a xml sitemap, easy way to manage the Google Analytics code and robots.txt on rootpage level',
	'category' => 'plugin',
	'author' => 'Leonie Philine Bitto [Netcreators], Arek van Schaijk',
	'author_email' => 'extensions@netcreators.nl',
	'state' => 'stable',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.6.0',
	'constraints' => [
		'depends' => [
			'typo3' => '7.6.15-7.6.99',
			'php' => '5.4.0-5.6.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];